# Generated by Django 5.0.6 on 2024-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climarica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, default='Autor', max_length=100, null=True),
        ),
    ]
