# Generated by Django 5.0.6 on 2024-06-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climarica', '0002_alter_noticia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
