# Generated by Django 5.0.6 on 2024-06-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climarica', '0003_boletim_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim',
            name='fonte',
            field=models.CharField(blank=True, default='https://www.marica.rj.gov.br/previsao-do-tempo/', max_length=100, null=True),
        ),
    ]
