# Generated by Django 5.0.6 on 2024-06-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climarica', '0004_boletim_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fonte',
            field=models.CharField(blank=True, default='Fonte', max_length=100, null=True),
        ),
    ]
